[package]
name = "sobel_filter"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25"

[[bin]]
name = "without_arc"
path = "src/without_arc.rs"

[[bin]]
name = "with_arc"
path = "src/with_arc.rs"